name: inner_breeze
description: Intuitive breathing tracker

publish_to: 'none'

version: 1.0.11+12

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  english_words: ^4.0.0
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9
  provider: ^6.0.0
  go_router: ^11.1.2
  syncfusion_flutter_sliders: ^23.1.38 
  window_manager: ^0.3.5
  uuid: ^3.0.7
  intl: ^0.18.0
  url_launcher: ^6.0.0
  just_audio: ^0.9.35
  just_audio_platform_interface: ^4.2.2
  just_audio_cache: ^0.1.2
  audio_session: ^0.1.17
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.7
  file_picker: ^5.2.10
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  wakelock_plus: ^1.1.3
  share_plus: ^7.2.1
  document_file_save_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/images/
    - assets/icons/
