name: innerbreeze
version: '1.0.0'
summary: Guided breathing meditation app
description: |
  InnerBreeze is a guided breathing meditation app to help you relax and focus.
  It provides multiple meditation techniques with visual and audio guides.

confinement: strict
base: core18
grade: stable

apps:
  innerbreeze:
    command: inner_breeze
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - unity7
      - wayland
      - pulseaudio
      - home
      - opengl
      - network

parts:
  innerbreeze:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
