name: Inner Breeze
version: '1.2.3'
summary: A meditation and breathing guide app
description: A dedicated meditation app designed to guide and track your Wim Hof Breathing practice.

grade: stable
base: core22
confinement: strict

apps:
  inner-breeze:
    command: inner_breeze
    extensions: [gnome]
    plugs:
      - network

parts:
  inner-breeze:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart