name: inner-breeze
version: '1.2.3'
summary: Inner Breeze
description: A dedicated meditation app designed to guide and track your Wim Hof Breathing practice.

grade: stable
base: core22
confinement: strict

apps:
  inner-breeze:
    command: inner_breeze
    common-id: io.naox.InnerBreeze
    extensions: [gnome]
    plugs:
      - network

parts:
  inner-breeze:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart    
    parse-info: [metadata/flatpak/io.naox.InnerBreeze.metainfo.xml]
