name: inbreeze
adopt-info: inbreeze

version: '1.3.5'
license: MIT
grade: stable
base: core20
confinement: strict
icon: snap/gui/io.naox.InnerBreeze.png

apps:
  inner-breeze:
    command: inner_breeze
    common-id: io.naox.InnerBreeze
    extensions: [gnome]
    plugs:
      - network

parts:
  inner-breeze:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart    
    parse-info: [metadata/io.naox.InnerBreeze.metainfo.xml]

  metainfo:
    source: .
    plugin: dump
    organize:
      metainfo.xml: metadata/io.naox.InnerBreeze.metainfo.xml
