name: inner-breeze
adopt-info: inner-breeze

version: '1.3.2'
license: MIT
grade: stable
base: core20
confinement: strict
icon: snap/gui/io.naox.InnerBreeze.png

apps:
  inner-breeze:
    command: bin/inner_breeze
    common-id: io.naox.InnerBreeze
    plugs:
      - network
      - desktop
      - wayland
      - x11
      - opengl
      - audio-playback

parts:
  inner-breeze:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - libgtk-3-dev
      - libglu1-mesa-dev
    stage-packages:
      - libgtk-3-0
      - libglib2.0-0
      - libpango-1.0-0
      - libcairo2
      - libx11-6
      - libgl1
      - libglu1-mesa
    parse-info: [metadata/io.naox.InnerBreeze.metainfo.xml]

  metainfo:
    source: .
    plugin: dump
    organize:
      metainfo.xml: metadata/io.naox.InnerBreeze.metainfo.xml
      