name: inner-breeze
adopt-info: inner-breeze-metainfo

version: '1.2.5'
license: MIT
grade: stable
base: core22
confinement: strict
icon: snap/gui/io.naox.InnerBreeze.png

apps:
  inner-breeze:
    command: inner_breeze
    common-id: io.naox.InnerBreeze
    extensions: [gnome]
    plugs:
      - network

parts:
  inner-breeze:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart    
  inner-breeze-metainfo:
    plugin: dump
    source: .
    parse-info: [local/io.naox.InnerBreeze.metainfo.xml]
