name: Inner Breeze
version: '1.2.3'
summary: A meditation and breathing guide app
description: A dedicated meditation app designed to guide and track your Wim Hof Breathing practice.

grade: stable
base: core22
confinement: strict


slots:
  dbus-inner-breeze:
    interface: dbus
    bus: session
    name: io.naox.InnerBreeze
 
apps:
  inner-breeze:
    command: inner_breeze
    extensions: [gnome]
    plugs:
      - network
    slots:
      - dbus-inner-breeze

parts:
  inner-breeze:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart