name: Build and Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7'
        
    - name: Install Dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --release --web-renderer canvaskit --base-href /inbe/
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
