name: Flutter APK Build

on:
  push:
    branches:
      - main # or the default branch name of your repository

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Create Release and Upload APK
      run: |
        gh release create ${{ github.sha }} build/app/outputs/flutter-apk/app-release.apk --title "Release ${{ github.sha }}" --notes "Release of ${{ github.sha }}"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        