name: "Release APK on Tag"

on:
  push:
    tags:
      - "**"

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Determine tag"
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: "Create release"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const response = await github.rest.repos.createRelease({
              draft: false,
              name: process.env.RELEASE_TAG,
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.RELEASE_TAG,
            });
            return response.data.upload_url;

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7'

      - name: "Install Dependencies"
        run: flutter pub get

      - name: "Build APK"
        run: flutter build apk --release

      - name: "Upload APK to Release"
        uses: "actions/upload-release-asset@v1"
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
